version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: whatpay
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: whatpay123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:whatpay123@postgres:5432/whatpay
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
